FROM node:22-alpine AS dev
WORKDIR /app

# Instala dependências (inclui devDependencies)
COPY package*.json ./
RUN npm install

# Copia todo código para dentro do container
COPY . .

# Expõe a porta do NestJS
EXPOSE 3333

# Roda o comando de dev do Nest no watch mode
CMD ["npm", "run", "start:dev"]
