app = "hiremate-api"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[[services]]
  internal_port = 3333
  protocol = "tcp"

  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

  # Health check HTTP em /healthz, sem autenticação
  [[services.http_checks]]
    interval      = "15s"      # a cada 15s
    timeout       = "2s"       # espera até 2s por resposta
    grace_period  = "15s"      # aguarda 15s antes de começar a checar
    method        = "GET"
    path          = "/healthz"
    protocol      = "http"
